### PR TITLE
Allow non-ASCII characters in comments 😅

### PR DESCRIPTION
**Pull request by tsujigiri**

### CODE REVIEW

**Comment by dziemba** [comment]
Why?

**Comment by tsujigiri** [comment]
In order to be able to enrich them.

**Comment by dziemba** [comment]
Enrich them with what? More emojis? 😄 
Can you give an example?

**Comment by RKushnir** [comment]
Like (╯°□°)╯︵ ┻━┻ ?

**Comment by tsujigiri** [comment]
Exactly! :laughing:

**Comment by tsujigiri** [comment]
Positive ones, too! E.g. :rainbow:!

**Comment by dziemba** [comment]
Sound like a horrible idea 😄 

👎 

What do @ad2games/devs think?

**Comment by RKushnir** [comment]
Meh

**Comment by tsujigiri** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by guigs** [comment]
Just create some ASCII Art

**Comment by purplejacket** [comment]
I want to have this comment in my code:

    # Software package 'a' depends on 'b' and 'd'
    #                  'b' depends on 'c' and 'e'
    #                  'c' depends on 'd' and 'e'
    #                  'd' depends on nothing
    #                  'e' depends on nothing
    #
    # It looks like this:
    #
    #      a
    #    ↙   ↘
    #  d       b
    #    ↖   ↙   ↘
    #      c   →   e


That's why.

**Comment by tsujigiri** [comment]
Everyone opposing this is gone, so... 😅

**Comment by RKushnir** [comment]
You waited long enough :tada:

**Pull request closed without merging**
