### PR TITLE
Disable AbcSize cop for migrations

### PR DESCRIPTION
**Pull request by RKushnir**

### CODE REVIEW

**Comment by tsujigiri** [comment]
Why? Migrations benefit from less cluttered code, too, no?

**Comment by RKushnir** [comment]
Imo, it doesn't make sense to disable `MethodLength`, but keep the `AbcSize`. If you have many lines, you likely also have many dots, because usually they look like `t.string :col`.
Or we could do the opposite — re-enable the `MethodLength`. WDYT?

**Comment by tsujigiri** [comment]
Good point! In general I think it's code, not really different from other code, so the same rules should apply, as far as they make sense. Not really sure in this case.

**Comment by RKushnir** [comment]
https://github.com/ad2games/rubocop-ci/pull/34 🙂

**Comment by tsujigiri** [comment]
@ad2games/devs Any other opinions?

**Comment by guigs** [comment]
I think that migrations are different from other code, because we don't have to maintain them and they run just once. Also they tend to be longer just because they have more columns. When we get a rubocop complain about MethodLength in migration what would you do? Disable it or try to refactor the migration? In rare cases it might be possible, but usually you would just disable it, so why not disable the rule for all migrations?

**Comment by RKushnir** [comment]
I don't have a strong opinion, because migrations are rarely written and read. Disabling the cop would save a small bit of hassle.

**Comment by StefanGreffenius** [comment]
Iam fine with both ways, have no strong opinion here either.

**Review by hwartig — APPROVED** [review]
I agree with @RKushnir. Lets :shipit:

I would ship this one and also keep the method length for migrations disabled.

**Pull request merged**
