### PR TITLE
Local rubocop config

### PR DESCRIPTION
**Pull request by avakarev**
In some cases in my project I want to skip some file from rubocop. In order of that I want to create my local .rubocop.yml file and I want it to be respected by "rake rubocop" task.

My local .rubocop.yml example:

``` yaml
AllCops:
  Exclude:
    - 'spec/dummy/db/schema.rb'
```

### CODE REVIEW

**Comment by dziemba** [comment]
The idea of this project is that we have a _global_ standardized rubocop config. Your `.rubocop.yml` should be merged into the global config in this repo, because it makes sense in all projects. 

Are there any use cases where we actually need this?

**Comment by avakarev** [comment]
Yes, I got the idea.
And in my case I don't want to change any rules, I just want to specify some particular files in my project to ignore by rubocop.

**Comment by dziemba** [comment]
Ignoring certain files is "changing the rules"... I'm fine with adding the dummy app schema to the ignored files in the global rubocop.yml, but I don't think that being able to add custom rules is a good idea (except for a `.rubocop_todo.yml` that is automatically generated)

**Comment by avakarev** [comment]
Agree.

**Pull request closed without merging**
