### PR TITLE
Two empty lines sometimes very useful. It would not be good to prevent them blindly.

### PR DESCRIPTION
**Pull request by zekefast**
For example:
- constants in classes and modules
- separating attributes in classes and modules
- let statements in specs

### CODE REVIEW

**Comment by RKushnir** [comment]
Could you provide some examples of the mentioned above? It doesn't sound convincing for me.

**Comment by dziemba** [comment]
Hmm. Can you give an example? I actually like the rule because often two blank lines are _not_ what you want...

**Comment by zekefast** [comment]
@dziemba 

``` ruby
::RSpec ::SomeClass do
  let(:let1) {...}
  let(:let2) {...}
  let(:let3) do

  end
  let(:let4) do

  end


  describe '.some_method' do
    context 'when cool' do
      it 'assert something' do
        expect

        expect
        expect

        call
      end
    end

    context 'when not so cool' do

    end
  end
end
```

**Comment by dziemba** [comment]
Doesn't convince me at all, I like it better without the double newline.

**Comment by tsujigiri** [comment]
Seems like a matter of being used to one way or the other. IMHO not reason enough to change it.

**Pull request closed without merging**
