### PR TITLE
Allow non-ASCII characters in comments 😅

### PR DESCRIPTION
**Pull request by tsujigiri**
[Since the one person who blocked this the laste time](https://github.com/ad2games/rubocop-ci/pull/16) is not working here anymore, let's try this again! 😏

If you are against this, you are a sad person! 😛

### CODE REVIEW

**Comment by RKushnir** [comment]
Why? 😄

**Comment by tsujigiri** [comment]
Because of the joy it brings.

**Review by RKushnir — COMMENTED** [review]
I'm not dying to put special chars in comments, but I also don't want to be a sad person.
Here's my non-disapproving *whatever* ¯\_(ツ)_/¯

**Review by guigs — APPROVED** [review]
`# 🌴`

**Pull request merged**
